import DefaultLayout from "@/layout/default";
import Image from "next/image";
import Loading from "./loading";
import { Button } from "@mui/joy";
import ComicItem from "@/components/comic/item";
import { Comic } from "@/@types/model/comic";
import Sidebar from "@/components/sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const FAKEDATA: Comic[] = [
  {
    image:
      "https://a-static.mlcdn.com.br/450x450/jujutsu-kaisen-batalha-de-feiticeiros-vol-8-capa-variante-panini/bgghqsemangas/14478795414/bbe317fce1a256857ffe46433e750e86.jpg",
    title: "Boruto -Two Blue Vortex-",
    description:
      'As "memórias" das pessoas foram alteradas e Boruto está numa posição onde a Vila Oculta da Folha quer tomar a sua vida. Durante essa adversidade, o que o aguardava quando deixou a vila com o Sasuke era...',
    episode: 5,
    views: 107189,
    languages: ["pt", "en"],
    owner: "MASASHI KISHIMOTO / MIKIO IKEMOTO",
    rating: 4.5,
  },
  {
    image:
      "https://cdn.awsli.com.br/2500x2500/838/838417/produto/200246994/tmpdragonballedicaodefinitiva12-e73802d41c.jpg",
    title: "Dragon Ball Super",
    description:
      "Having defeated Boo, Goku is starting to get bored with his life on Earth. His wife, Chi-chi, wants him to get a job, but all he wants to do is train and fight stronger enemies. Elsewhere in the universe, the God of Destruction, Beerus, and his attendant Whis are traveling from planet to planet in search of food and entertainment. After blowing up some hapless victims, Beerus is reminded of a man from his dreams with the moniker “Super Saiyan God,” or something like that... The God of Destruction sets his sights on Earth to track down this mysterious man! Maybe this will give Goku something to do?",
    episode: 100,
    views: 299939,
    languages: ["pt", "en"],
    owner: "AKIRA TORIYAMA / TOYOTAROU",
    rating: 4.5,
  },
  {
    image: "https://pbs.twimg.com/media/EY6iaOAX0AYhGi3.jpg",
    title: "[OSHI NO KO]",
    description: "",
    episode: 135,
    views: 309844,
    languages: ["pt", "en"],
    owner: "AKA AKASAKA X MENGO YOKOYARI",
    rating: 4.5,
  },
  {
    image:
      "https://http2.mlstatic.com/D_NQ_NP_800770-MLU50423210183_062022-O.webp",
    title: "Choujin X",
    description:
      "A new infection has spread around the planet, that turns people into undead. The story begins a few minutes before the first recorded case, and shows the struggle of six young to survive this new world.",
    episode: 46,
    views: 4232,
    languages: ["pt", "en"],
    owner: "SUI ISHIDA",
    rating: 4.5,
  },
  {
    image:
      "https://i.pinimg.com/236x/77/23/7f/77237fd30c5a8ab7eee9e17e58ee963f.jpg",
    title: "Kindergarten WARS",
    description:
      "A new infection has spread around the planet, that turns people into undead. The story begins a few minutes before the first recorded case, and shows the struggle of six young to survive this new world.",
    episode: 58,
    views: 91641,
    languages: ["pt", "en"],
    owner: "YOU CHIBA",
    rating: 4.5,
  },
  {
    image: "https://i.imgur.com/s22QNCG.jpg",
    title: "The Game Devil",
    description:
      "A new infection has spread around the planet, that turns people into undead. The story begins a few minutes before the first recorded case, and shows the struggle of six young to survive this new world.",
    episode: 1,
    views: 38528,
    languages: ["pt", "en"],
    owner: "KAKUNOSHIN FUTSUZAWA",
    rating: 4.5,
  },
  {
    image:
      "https://www.intoxianime.com/wp-content/uploads/2018/11/Capas-Mang%C3%A1-41-3-1.jpg",
    title: "Boruto -Two Blue Vortex-",
    description:
      'As "memórias" das pessoas foram alteradas e Boruto está numa posição onde a Vila Oculta da Folha quer tomar a sua vida. Durante essa adversidade, o que o aguardava quando deixou a vila com o Sasuke era...',
    episode: 5,
    views: 107189,
    languages: ["pt", "en"],
    owner: "MASASHI KISHIMOTO / MIKIO IKEMOTO",
    rating: 4.5,
  },
];
export default function Home() {
  return (
    <DefaultLayout>
      <div className="flex just gap-4 pt-[10%] w-4/5 mx-auto">
        <div className="bg-grey-900 pl-8 pr-4">
          <div className="w-full flex justify-between py-6">
            <h2 className="text-2xl font-bold text-white">
              Atualizações Diárias
            </h2>
            <Button className="bg-blue-600 hover:bg-blue-800 transition-colors font-semibold">
              Ver Mais
            </Button>
          </div>
          <div className="grid grid-cols-6 flex-gap flex-wrap gap-x-2 gap-y-5">
            {FAKEDATA.map((comic, i) => (
              <ComicItem
                key={comic.title}
                comic={comic}
                flag={i % 3 === 0 ? "novo" : undefined}
              />
            ))}
            {FAKEDATA.map((comic, i) => (
              <ComicItem
                key={comic.title}
                comic={comic}
                flag={i % 3 === 0 ? "popular" : undefined}
              />
            ))}
            {FAKEDATA.map((comic, i) => (
              <ComicItem
                key={comic.title}
                comic={comic}
                flag={i % 3 === 0 ? "atualizou" : undefined}
              />
            ))}
            {FAKEDATA.map((comic, i) => (
              <ComicItem
                key={comic.title}
                comic={comic}
                flag={i % 3 === 0 ? "top" : undefined}
              />
            ))}
          </div>
        </div>
        <div className="flex-1 min-w-80 rounded-md">
          <Sidebar />
        </div>
      </div>
    </DefaultLayout>
  );
}
